/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorPrincipal;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import modelo.vo.Arma;
import modelo.vo.Mod;
import modelo.vo.Warframe;

/**
 *
 * @author aizpu
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_menu = new javax.swing.JPanel();
        btn_armas = new javax.swing.JButton();
        btn_warframes = new javax.swing.JButton();
        panel_pantalla = new javax.swing.JPanel();
        panel_armas = new javax.swing.JPanel();
        cmb_armas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        label10 = new javax.swing.JLabel();
        label11 = new javax.swing.JLabel();
        label12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmb_mods_1 = new javax.swing.JComboBox<>();
        cmb_mods_3 = new javax.swing.JComboBox<>();
        cmb_mods_2 = new javax.swing.JComboBox<>();
        cmb_mods_4 = new javax.swing.JComboBox<>();
        cmb_mods_5 = new javax.swing.JComboBox<>();
        cmb_mods_6 = new javax.swing.JComboBox<>();
        cmb_mods_7 = new javax.swing.JComboBox<>();
        cmb_mods_8 = new javax.swing.JComboBox<>();
        panel_warframes = new javax.swing.JPanel();
        cmb_warframes = new javax.swing.JComboBox<>();
        panel_builds = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        btn_armas.setText("Armas");
        btn_armas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_armasActionPerformed(evt);
            }
        });

        btn_warframes.setText("Warframes");
        btn_warframes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_warframesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_menuLayout = new javax.swing.GroupLayout(panel_menu);
        panel_menu.setLayout(panel_menuLayout);
        panel_menuLayout.setHorizontalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(btn_armas)
                .addGap(38, 38, 38)
                .addComponent(btn_warframes)
                .addContainerGap(496, Short.MAX_VALUE))
        );
        panel_menuLayout.setVerticalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_armas)
                    .addComponent(btn_warframes))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(panel_menu, java.awt.BorderLayout.PAGE_START);

        panel_pantalla.setLayout(new java.awt.CardLayout());

        cmb_armas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_armasActionPerformed(evt);
            }
        });

        jLabel1.setText("Selecciona el arma");

        label1.setText("label 1");

        label2.setText("label 2");

        label3.setText("label 3");

        label4.setText("label 4");

        label5.setText("label 5");

        label6.setText("label 6");

        label7.setText("label 7");

        label8.setText("label 8");

        label9.setText("label 9");

        label10.setText("label 10");

        label11.setText("label 11");

        label12.setText("label 12");

        jLabel2.setText("Mod 1");

        jLabel3.setText("Mod 3");

        jLabel4.setText("Mod 5");

        jLabel5.setText("Mod 2");

        jLabel6.setText("Mod 4");

        jLabel7.setText("Mod 7");

        jLabel8.setText("Mod 8");

        jLabel9.setText("Mod 6");

        cmb_mods_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_mods_1ActionPerformed(evt);
            }
        });

        cmb_mods_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_mods_3ActionPerformed(evt);
            }
        });

        cmb_mods_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_mods_2ActionPerformed(evt);
            }
        });

        cmb_mods_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_mods_4ActionPerformed(evt);
            }
        });

        cmb_mods_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_mods_5ActionPerformed(evt);
            }
        });

        cmb_mods_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_mods_6ActionPerformed(evt);
            }
        });

        cmb_mods_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_mods_7ActionPerformed(evt);
            }
        });

        cmb_mods_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_mods_8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_armasLayout = new javax.swing.GroupLayout(panel_armas);
        panel_armas.setLayout(panel_armasLayout);
        panel_armasLayout.setHorizontalGroup(
            panel_armasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_armasLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panel_armasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_armasLayout.createSequentialGroup()
                        .addGroup(panel_armasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_armasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panel_armasLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(183, 183, 183)
                                    .addComponent(jLabel8))
                                .addGroup(panel_armasLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(183, 183, 183)
                                    .addComponent(jLabel5)))
                            .addGroup(panel_armasLayout.createSequentialGroup()
                                .addGroup(panel_armasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmb_mods_3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(cmb_mods_5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(panel_armasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmb_mods_6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(cmb_mods_4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(panel_armasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label5)
                            .addComponent(label4)
                            .addComponent(label2)
                            .addGroup(panel_armasLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(32, 32, 32)
                                .addComponent(cmb_armas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_armasLayout.createSequentialGroup()
                                .addGroup(panel_armasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label1)
                                    .addComponent(label3)
                                    .addComponent(label6))
                                .addGap(111, 111, 111)
                                .addGroup(panel_armasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label12)
                                    .addComponent(label8)
                                    .addComponent(label7)
                                    .addComponent(label9)
                                    .addComponent(label10)
                                    .addComponent(label11))))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_armasLayout.createSequentialGroup()
                        .addComponent(cmb_mods_7, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(cmb_mods_8, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_armasLayout.createSequentialGroup()
                        .addGroup(panel_armasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_mods_1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(panel_armasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(cmb_mods_2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panel_armasLayout.setVerticalGroup(
            panel_armasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_armasLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panel_armasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_armas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGroup(panel_armasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_armasLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(panel_armasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label1)
                            .addComponent(label7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_armasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label2)
                            .addComponent(label8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_armasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label3)
                            .addComponent(label9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_armasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label4)
                            .addComponent(label10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_armasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label5)
                            .addComponent(label11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_armasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label6)
                            .addComponent(label12)))
                    .addGroup(panel_armasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_armasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_armasLayout.createSequentialGroup()
                                .addGroup(panel_armasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmb_mods_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_mods_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_armasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_mods_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_mods_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_armasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_armasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_mods_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_mods_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(panel_armasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_armasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_mods_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_mods_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        panel_pantalla.add(panel_armas, "card4");

        cmb_warframes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_warframesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_warframesLayout = new javax.swing.GroupLayout(panel_warframes);
        panel_warframes.setLayout(panel_warframesLayout);
        panel_warframesLayout.setHorizontalGroup(
            panel_warframesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_warframesLayout.createSequentialGroup()
                .addContainerGap(656, Short.MAX_VALUE)
                .addComponent(cmb_warframes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        panel_warframesLayout.setVerticalGroup(
            panel_warframesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_warframesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(cmb_warframes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(378, Short.MAX_VALUE))
        );

        panel_pantalla.add(panel_warframes, "card3");

        javax.swing.GroupLayout panel_buildsLayout = new javax.swing.GroupLayout(panel_builds);
        panel_builds.setLayout(panel_buildsLayout);
        panel_buildsLayout.setHorizontalGroup(
            panel_buildsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 846, Short.MAX_VALUE)
        );
        panel_buildsLayout.setVerticalGroup(
            panel_buildsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        panel_pantalla.add(panel_builds, "card2");

        jPanel1.add(panel_pantalla, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        ControladorPrincipal.cerrarFactory();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ControladorPrincipal.cargarArmas();
        ControladorPrincipal.cargarWarframes();
        ControladorPrincipal.cargarMods();
    }//GEN-LAST:event_formWindowOpened

    private void btn_armasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_armasActionPerformed
        panel_pantalla.removeAll();
        panel_pantalla.add(panel_armas);
        panel_pantalla.repaint();
        panel_pantalla.revalidate();
    }//GEN-LAST:event_btn_armasActionPerformed

    private void btn_warframesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_warframesActionPerformed
        panel_pantalla.removeAll();
        panel_pantalla.add(panel_warframes);
        panel_pantalla.repaint();
        panel_pantalla.revalidate();
    }//GEN-LAST:event_btn_warframesActionPerformed

    private void cmb_warframesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_warframesActionPerformed
        
    }//GEN-LAST:event_cmb_warframesActionPerformed

    private void cmb_armasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_armasActionPerformed
        ControladorPrincipal.cargarStatsBaseArma();
        ControladorPrincipal.resetearCombosMods();
    }//GEN-LAST:event_cmb_armasActionPerformed

    private void cmb_mods_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_mods_1ActionPerformed
        ControladorPrincipal.actualizarStatsArma();
    }//GEN-LAST:event_cmb_mods_1ActionPerformed

    private void cmb_mods_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_mods_2ActionPerformed
        ControladorPrincipal.actualizarStatsArma();
    }//GEN-LAST:event_cmb_mods_2ActionPerformed

    private void cmb_mods_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_mods_3ActionPerformed
        ControladorPrincipal.actualizarStatsArma();
    }//GEN-LAST:event_cmb_mods_3ActionPerformed

    private void cmb_mods_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_mods_4ActionPerformed
        ControladorPrincipal.actualizarStatsArma();
    }//GEN-LAST:event_cmb_mods_4ActionPerformed

    private void cmb_mods_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_mods_5ActionPerformed
        ControladorPrincipal.actualizarStatsArma();
    }//GEN-LAST:event_cmb_mods_5ActionPerformed

    private void cmb_mods_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_mods_6ActionPerformed
        ControladorPrincipal.actualizarStatsArma();
    }//GEN-LAST:event_cmb_mods_6ActionPerformed

    private void cmb_mods_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_mods_7ActionPerformed
        ControladorPrincipal.actualizarStatsArma();
    }//GEN-LAST:event_cmb_mods_7ActionPerformed

    private void cmb_mods_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_mods_8ActionPerformed
        ControladorPrincipal.actualizarStatsArma();
    }//GEN-LAST:event_cmb_mods_8ActionPerformed

    public JComboBox<Arma> getCmb_armas() {
        return cmb_armas;
    }

    public void setCmb_armas(JComboBox<Arma> cmb_armas) {
        this.cmb_armas = cmb_armas;
    }

    public JComboBox<Warframe> getCmb_warframes() {
        return cmb_warframes;
    }

    public void setCmb_warframes(JComboBox<Warframe> cmb_warframes) {
        this.cmb_warframes = cmb_warframes;
    }
 
    public JLabel[] getLabelsArray() {
        return new JLabel[]{label1,label2,label3,label4,label5,label6,
                label7,label8,label9,label10,label11,label12};
    }
    
    public JComboBox[] getCombosMods() {
        return new JComboBox[]{ cmb_mods_1, cmb_mods_2, cmb_mods_3, cmb_mods_4, cmb_mods_5, cmb_mods_6, cmb_mods_7, cmb_mods_8 };
    }
    
    public String[] getOrdenStats() {
        return new String[]{"impacto", "perforante", "cortante", "frio", "electrico", "calor", "toxina", "critico", "mult_critico", "estado", "precision", "cadencia" };
    }
    
    private Map<String, Double> statsBase = new HashMap<>();
    
    public void setValorBase(String stat, double valor) {
        statsBase.put(stat, valor);
    }

    public double getValorBase(String stat) {
        return statsBase.getOrDefault(stat, 0.0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_armas;
    private javax.swing.JButton btn_warframes;
    private javax.swing.JComboBox<Arma> cmb_armas;
    private javax.swing.JComboBox<Mod> cmb_mods_1;
    private javax.swing.JComboBox<Mod> cmb_mods_2;
    private javax.swing.JComboBox<Mod> cmb_mods_3;
    private javax.swing.JComboBox<Mod> cmb_mods_4;
    private javax.swing.JComboBox<Mod> cmb_mods_5;
    private javax.swing.JComboBox<Mod> cmb_mods_6;
    private javax.swing.JComboBox<Mod> cmb_mods_7;
    private javax.swing.JComboBox<Mod> cmb_mods_8;
    private javax.swing.JComboBox<Warframe> cmb_warframes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    public javax.swing.JPanel panel_armas;
    private javax.swing.JPanel panel_builds;
    private javax.swing.JPanel panel_menu;
    private javax.swing.JPanel panel_pantalla;
    private javax.swing.JPanel panel_warframes;
    // End of variables declaration//GEN-END:variables
}
